### ISSUE TITLE
OSError: [Errno 36] File name too long:

### ISSUE THREAD

**Issue by ghost** [Haaxmax/WaybackPDF#1]
Having a problem whereby the filename of the pdf document is too long and so it stops downloading the PDFs

**Comment by Haax9** [comment]
Hey,
Interesting!
Could you please give an example ? 
I'm gonna try to reproduce and see how can we patch this :)

**Comment by ghost** [comment]
The example I have is a little awkward because its quite a few pdfs you would need to get to before you get the error. I do believe that the issue is because the script is trying to save a file that has more than 255 characters which is the max file name for a file in linux

`Traceback (most recent call last):
  File "waybackPDF.py", line 132, in <module>
    main()
  File "waybackPDF.py", line 125, in main
    downloadFiles(args.domain, pdfList, outputDir)
  File "waybackPDF.py", line 101, in downloadFiles
    with open(output + '/' + pdf['name'],'wb') as file:
OSError: [Errno 36] File name too long: '<A really long file name.pdf>`

**Comment by Haax9** [comment]
Thanks for your reply.
I'm thinking about a quick&dirty fix. I'll try it when I'll have some free time!

**Comment by ghost** [comment]
Yeah this is a real pain because it will stop the download, and the I have to start over again, but then I will have the same issue of when it gets to the pdf with the long filename it will stop downloading. So I will never be able to get past that pdf with the long filename

**Comment by Haax9** [comment]
Hey,
Pushed a new version. I didn't find any example on the Wayback Machine so I simulated a test. Please let me know if it works!
Also added a new option in order to skip previously downloaded files.

**Comment by ghost** [comment]
HI,
I can confirm that the new version has fixed the issue of very long file names, I think the issue was because the filename was in a different language and so it would use bytes as the filename.
Thanks!
