### ISSUE TITLE
Continue downloading pdfs where it left off if it was interrupted during download Feature Request

### ISSUE THREAD

**Issue by ghost** [Haaxmax/WaybackPDF#2]
It would be really cool if the script was able to continue to download the pdfs where it left off from last time instead of having to start downloading all the pdfs again if it was interrupted during download

**Comment by Haax9** [comment]
Hey,
In case of large scopes, you're right, it could be an interesting feature. I'll look at it for the future!

**Comment by Haax9** [comment]
Hey!
Just added a new option allowing you to start downloading at a specific index.

Just provide the file number where you want to start and the previous ones will be omitted.
Let me know if it's ok!

**Comment by ghost** [comment]
Hi, 
I can confirm that this works fine
Thanks!
